# Generated by Django 2.2.1 on 2019-05-19 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mwa_usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")]),
        ),
    ]
