# Generated by Django 2.2.2 on 2019-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwa_usermodel',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
