# Generated by Django 2.2.1 on 2019-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_users', '0002_auto_20190519_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mwa_usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
