# Generated by Django 2.2.2 on 2019-06-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodities',
            name='display_order',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
