# Generated by Django 2.2.1 on 2019-05-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodities',
            name='affiliate_link',
            field=models.URLField(blank=True, help_text='Link to where user can buy this commodity', null=True),
        ),
    ]
