# Generated by Django 2.2.1 on 2019-05-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodities',
            name='shortname',
        ),
    ]
