# Generated by Django 2.2.1 on 2019-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodities',
            name='file',
        ),
        migrations.AddField(
            model_name='commodities',
            name='enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
