# Generated by Django 2.2.2 on 2019-07-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0002_commodities_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodities',
            name='historical_data',
            field=models.FileField(blank=True, help_text="historical data in csv format (don't change column names or format)", null=True, upload_to='datasets/'),
        ),
    ]
