# Generated by Django 2.2.1 on 2019-05-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0002_commodities_affiliate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodities',
            name='affiliate_link',
        ),
    ]
