# Generated by Django 2.2.1 on 2019-05-16 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0003_auto_20190516_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='date_last_scraped',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
