# Generated by Django 2.2.1 on 2019-05-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0004_auto_20190516_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodities',
            name='shortname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
