# Generated by Django 2.2.2 on 2019-07-10 08:54

import MWA_webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0004_commodities_historical_data_apiendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='historical_data',
            field=models.FileField(blank=True, help_text="historical data in csv format (don't change column names or format)", null=True, storage=MWA_webapp.models.MyFileStorage(), upload_to='datasets/'),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='historical_data_APIendpoint',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
