# Generated by Django 2.2.1 on 2019-05-16 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0005_commodities_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='date_last_scraped',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
