# Generated by Django 2.2.2 on 2020-01-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0006_commodity_ts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity_ts',
            old_name='commodity_name',
            new_name='name',
        ),
    ]
