# Generated by Django 2.2.2 on 2020-01-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWA_webapp', '0007_auto_20200123_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_ts',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commodity_ts',
            name='name',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Oil', 'Oil'), ('Allords', 'Allords'), ('Allordsperatio', 'Allordsperatio'), ('Bitcoin', 'Bitcoin'), ('AUD', 'AUD')], max_length=20),
        ),
    ]
